import {AbsoluteFill, Img, Sequence, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig} from "remotion";

const C = {paper: "#0a0b0e", ink: "#f5f5f7", muted: "rgba(245,245,247,.68)", uiInk: "#17251c", uiMuted: "#667068", line: "#d8d4c9", green: "#8fc99c", uiGreen: "#315c3b", pale: "#e7eadc", red: "#d92820", orange: "#dc7b16"};
const ui = "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Helvetica Neue', sans-serif";
const editorial = "Iowan Old Style, 'Times New Roman', serif";
const enter = (frame, fps, delay = 0) => spring({frame, fps, delay, config: {damping: 180}});

const Frame = ({children}) => <AbsoluteFill style={{background: C.paper, color: C.ink, fontFamily: ui, overflow: "hidden"}}><Img src={staticFile("orchard.png")} style={{position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover", filter: "saturate(68%) contrast(90%) brightness(72%)"}} /><AbsoluteFill style={{background: "rgba(7,8,12,.56)"}} /><AbsoluteFill style={{opacity: .13, backgroundImage: "radial-gradient(rgba(255,255,255,.32) .6px, transparent .6px)", backgroundSize: "4px 4px"}} />{children}</AbsoluteFill>;

const Brand = ({compact}) => <div style={{position: "absolute", top: compact ? 34 : 44, left: compact ? 48 : 58, display: "flex", alignItems: "center", gap: 13, zIndex: 20}}><Img src={staticFile("hig-doctor-icon.svg")} style={{width: 31, height: 31, objectFit: "contain"}} /><div><div style={{fontSize: 20, fontWeight: 700, lineHeight: 1}}>HIG Doctor</div><div style={{fontSize: 13, color: C.muted, marginTop: 5, fontWeight: 550}}>Raintree Technology</div></div></div>;

const Phone = ({after = false, compact}) => <div style={{width: compact ? 250 : 280, height: compact ? 530 : 590, border: "8px solid #171a18", borderRadius: 38, background: "#fff", color: C.uiInk, padding: "30px 12px 12px", boxShadow: "0 22px 60px rgba(0,0,0,.38)", position: "relative", flexShrink: 0}}>
  <div style={{position: "absolute", top: 10, left: "50%", transform: "translateX(-50%)", width: 78, height: 18, borderRadius: 12, background: "#111"}} />
  <div style={{display: "flex", justifyContent: "space-between", alignItems: "center", fontSize: 13, fontWeight: 700, borderBottom: `1px solid ${C.line}`, padding: "6px 3px 12px"}}><span>Menu</span><span style={{fontSize: 17}}>Shop</span><span>Cart · {after ? "1" : "3"}</span></div>
  {after ? <><div style={{background: C.pale, borderRadius: 13, padding: 14, marginTop: 12, height: compact ? 150 : 170, position: "relative", overflow: "hidden"}}><div style={{fontSize: 12, color: C.uiMuted}}>Summer picks</div><div style={{fontFamily: editorial, fontSize: 24, lineHeight: 1.02, marginTop: 6, width: 130}}>Up to 70% off</div><div style={{fontSize: 10, color: C.uiMuted, marginTop: 8}}>Limited time only.</div><div style={{display: "inline-block", color: "#fff", background: C.uiGreen, borderRadius: 6, padding: "7px 11px", fontSize: 11, fontWeight: 700, marginTop: 10}}>Shop now</div><Img src={staticFile("headphones-olive.png")} style={{position: "absolute", width: 120, height: 120, objectFit: "contain", right: -2, bottom: 0}} /></div><div style={{border: `1px solid ${C.line}`, borderRadius: 10, color: "#929892", fontSize: 11, padding: "10px 12px", marginTop: 11}}>Search products…</div></> : <><div style={{color: "#fff", background: C.red, borderRadius: 9, padding: "9px 8px", marginTop: 12, textAlign: "center", fontSize: 11, fontWeight: 800}}>FLASH SALE — 70% OFF EVERYTHING!</div><div style={{color: "#fff", background: C.red, borderRadius: 5, padding: 7, margin: "7px 35px 0", textAlign: "center", fontSize: 11, fontWeight: 800}}>SHOP NOW</div><div style={{border: `1px solid ${C.line}`, borderRadius: 10, color: "#929892", fontSize: 11, padding: "10px 12px", marginTop: 10}}>Search products…</div></>}
  <div style={{fontFamily: editorial, fontSize: 20, marginTop: 14, fontWeight: 700}}>Popular</div><div style={{border: `1px solid ${C.line}`, borderRadius: 13, padding: 11, marginTop: 8, display: "flex", alignItems: "center", gap: 8}}><Img src={staticFile("headphones-olive.png")} style={{width: 72, height: 72, objectFit: "contain"}} /><div><div style={{fontSize: 11, fontWeight: 700}}>Wireless Headphones</div><div style={{fontSize: 14, fontWeight: 800, marginTop: 5}}>$59.99</div><div style={{display: "inline-block", color: "#fff", background: after ? C.uiGreen : C.red, borderRadius: 5, padding: "3px 6px", fontSize: 9, marginTop: 5}}>-70%</div></div></div>
  {!after && <div style={{position: "absolute", left: 11, right: 11, bottom: 13, background: "#fff", border: `1px solid ${C.line}`, borderRadius: 13, padding: 14, boxShadow: "0 0 25px rgba(0,0,0,.18)"}}><div style={{fontFamily: editorial, fontWeight: 800, textAlign: "center"}}>Subscribe & Save!</div><div style={{color: C.uiMuted, fontSize: 9, textAlign: "center", marginTop: 5}}>Get exclusive deals and updates.</div><div style={{background: C.red, color: "#fff", borderRadius: 6, padding: 9, textAlign: "center", fontSize: 11, fontWeight: 800, marginTop: 10}}>Subscribe Now!!!</div></div>}
  {after && <div style={{position: "absolute", left: 18, right: 18, bottom: 16, display: "flex", justifyContent: "space-between", color: C.uiMuted, fontSize: 10}}><b style={{color: C.uiGreen}}>Home</b><span>Categories</span><span>Favorites</span><span>Profile</span></div>}
</div>;

const AuditCard = ({compact}) => {const findings = [["Weak visual hierarchy", "Competing elements and inconsistent emphasis", C.red], ["Hard-coded color", "Non-system colors reduce flexibility", C.orange], ["Small tap target", "Interactive element is below 44pt", C.orange], ["Intrusive modal", "Blocks task flow before intent is established", C.red]]; return <div style={{width: compact ? 300 : 330, height: compact ? 530 : 590, color: C.ink, background: "rgba(28,30,38,.78)", backdropFilter: "blur(40px) saturate(180%)", border: "1px solid rgba(255,255,255,.11)", borderRadius: 24, padding: compact ? 20 : 24, boxShadow: "0 22px 60px rgba(0,0,0,.38)", flexShrink: 0}}><div style={{display: "flex", alignItems: "center", gap: 10, borderBottom: "1px solid rgba(255,255,255,.1)", paddingBottom: 15}}><Img src={staticFile("hig-doctor-icon.svg")} style={{width: 30, height: 30}} /><div><div style={{fontSize: 17, fontWeight: 700}}>Audit Report</div><div style={{fontSize: 11, color: C.muted}}>4 reviewable findings</div></div></div><div style={{display: "grid", gap: compact ? 9 : 11, marginTop: 15}}>{findings.map(([title, body, color], i) => <div key={title} style={{background: "rgba(255,255,255,.035)", border: "1px solid rgba(255,255,255,.09)", borderRadius: 12, padding: compact ? 11 : 13}}><div style={{display: "flex", gap: 9}}><div style={{width: 9, height: 9, borderRadius: "50%", background: color, marginTop: 4, flexShrink: 0}} /><div><div style={{fontSize: 13, fontWeight: 700}}>{title}</div><div style={{color: C.muted, fontSize: 10, lineHeight: 1.35, marginTop: 4}}>{body}</div><div style={{color: C.green, fontFamily: "ui-monospace, monospace", fontSize: 9, marginTop: 5}}>Storefront.tsx:{12 + i * 9}</div></div></div></div>)}</div></div>};

const Hero = ({compact}) => {const frame = useCurrentFrame(); const {fps} = useVideoConfig(); const p = enter(frame, fps, 4); return <AbsoluteFill style={{padding: compact ? "110px 48px 80px" : "130px 58px 95px", justifyContent: "center", alignItems: "center", textAlign: "center"}}><div style={{opacity: p, transform: `translateY(${interpolate(p, [0, 1], [18, 0])}px)`}}><div style={{fontSize: compact ? 70 : 80, fontWeight: 650, lineHeight: 1.02, letterSpacing: "-.04em"}}>Teach your AI<br />Apple’s design language.</div><div style={{fontSize: compact ? 23 : 26, fontWeight: 500, color: C.muted, lineHeight: 1.35, marginTop: 26}}>Give your AI the complete Apple Human Interface Guidelines.<br />No more hallucinated patterns. No more wrong-platform advice.</div><div style={{display: "flex", justifyContent: "center", gap: 14, marginTop: 38}}>{[["431", "audit rules"], ["14", "frameworks"], ["156", "HIG topics"]].map(([v,l]) => <div key={l} style={{border: "1px solid rgba(255,255,255,.1)", borderRadius: 14, padding: "13px 20px", background: "rgba(28,30,38,.58)", backdropFilter: "blur(32px)"}}><b style={{fontSize: 26, color: C.ink}}>{v}</b><div style={{fontSize: 11, color: C.muted}}>{l}</div></div>)}</div></div></AbsoluteFill>};

const Demo = ({compact}) => {const frame = useCurrentFrame(); const {fps} = useVideoConfig(); const left = enter(frame, fps), middle = enter(frame, fps, 12), right = enter(frame, fps, 28); const gap = compact ? 20 : 28; return <AbsoluteFill style={{padding: compact ? "105px 42px 85px" : "120px 50px 95px", justifyContent: "center"}}><div style={{fontSize: compact ? 44 : 50, fontWeight: 650, letterSpacing: "-.035em", textAlign: "center", marginBottom: 26}}>See the difference.</div><div style={{display: "flex", alignItems: "center", justifyContent: "center", gap}}><div style={{opacity: left, transform: `translateX(${interpolate(left,[0,1],[-20,0])}px)`}}><div style={{textAlign: "center", fontSize: 14, fontWeight: 700, color: "#ff8b85", marginBottom: 9}}>WITHOUT GUIDANCE</div><Phone compact={compact} /></div><div style={{opacity: middle, transform: `translateY(${interpolate(middle,[0,1],[18,0])}px)`}}><div style={{textAlign: "center", fontSize: 14, fontWeight: 700, color: C.muted, marginBottom: 9}}>HIG DOCTOR</div><AuditCard compact={compact} /></div><div style={{opacity: right, transform: `translateX(${interpolate(right,[0,1],[20,0])}px)`}}><div style={{textAlign: "center", fontSize: 14, fontWeight: 700, color: C.green, marginBottom: 9}}>GROUNDED IN APPLE HIG</div><Phone after compact={compact} /></div></div></AbsoluteFill>};

const Cta = ({compact}) => {const frame = useCurrentFrame(); const {fps} = useVideoConfig(); const p = enter(frame, fps, 2); return <AbsoluteFill style={{alignItems: "center", justifyContent: "center", textAlign: "center", padding: 70}}><div style={{opacity: p, transform: `scale(${interpolate(p,[0,1],[.94,1])})`}}><Img src={staticFile("hig-doctor-icon.svg")} style={{width: compact ? 88 : 102, height: compact ? 88 : 102}} /><div style={{fontSize: compact ? 64 : 74, fontWeight: 650, letterSpacing: "-.04em", lineHeight: 1, marginTop: 28}}>Accurate guidance.<br />Every Apple platform.</div><div style={{color: C.muted, fontSize: compact ? 22 : 25, fontWeight: 500, marginTop: 22}}>Install now — it’s free.</div><div style={{display: "inline-block", color: C.ink, background: "rgba(28,30,38,.72)", backdropFilter: "blur(36px)", border: "1px solid rgba(255,255,255,.11)", fontFamily: "ui-monospace, monospace", borderRadius: 13, padding: "17px 21px", fontSize: compact ? 18 : 21, marginTop: 30}}>npx skills add raintree-technology/hig-doctor</div><div style={{color: C.muted, fontSize: 17, marginTop: 22}}>6,000+ installs · 118 GitHub stars</div></div></AbsoluteFill>};

const Fade = ({duration, children}) => {const frame = useCurrentFrame(); const opacity = interpolate(frame, [0, 12, duration - 12, duration], [0, 1, 1, 0], {extrapolateLeft: "clamp", extrapolateRight: "clamp"}); return <AbsoluteFill style={{opacity}}>{children}</AbsoluteFill>};

export const SocialPromo = ({platform = "linkedin"}) => {const compact = platform === "x"; return <Frame><Brand compact={compact} /><Sequence durationInFrames={120}><Fade duration={120}><Hero compact={compact} /></Fade></Sequence><Sequence from={100} durationInFrames={245} premountFor={30}><Fade duration={245}><Demo compact={compact} /></Fade></Sequence><Sequence from={325} durationInFrames={215} premountFor={30}><Fade duration={215}><Cta compact={compact} /></Fade></Sequence></Frame>};
